version: '3.8'

services:
  ##### FRONTEND (NodeJS React) #####
  frontend:
    container_name: moti-is24-written-assessment-jaeung_kim-frontend
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - moti-is24-written-assessment-jaeung_kim-network
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  ##### BACKEND (NodeJS Express API) #####
  backend:
    container_name: moti-is24-written-assessment-jaeung_kim-backend
    tty: true
    init: true # Properly handles running as PID 1 inside a container. Source: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - moti-is24-written-assessment-jaeung_kim-network
    ports:
      - 3030:3030
    volumes:
      - ./backend:/app
    environment:
      - PORT=8008
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:3030
    depends_on:
      - mongo
    ##### MONGODB #####
  mongo:
    container_name: moti-is24-written-assessment-jaeung_kim-mongo
    image: mongo:latest
    restart: on-failure
    networks:
      - moti-is24-written-assessment-jaeung_kim-network
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

networks:
  moti-is24-written-assessment-jaeung_kim-network:
    driver: bridge

volumes:
  mongo-data: